### ISSUE TITLE
wxPython 3.0 breaks Application Manager

### ISSUE THREAD

**Issue by mejohn** [ncsurobotics/seawolf#31]
Max install of wxPython is 2.8 for now. Debian Jessie repos only contain 3.0. Upgrade application manager eventually.

**Comment by smosh** [comment]
Error encountered when running seawolf/run.py (application manager) with newly installed debian jessie and latest packages:

    Traceback (most recent call last):
    File "run.py", line 452, in <module>
        frame = AppRunnerFrame(None, -1, "Application Runner", size=wx.Size(1000, 400))
    File "run.py", line 40, in __init__
        self.app_tree.SelectItem(self.app_tree.GetFirstVisibleItem())
    File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_controls.py", line 5509, in SelectItem
        return _controls_.TreeCtrl_SelectItem(*args, **kwargs)
    wx._core.PyAssertionError: C++ assertion "item" failed at ../src/generic/treectlg.cpp(2209) in SelectItem(): SelectItem(): invalid tree item

Noticed that Commenting out line 40 of seawolf/run.py seems to fix this:

        ...
    38  self.app_tree.Bind(wx.EVT_TREE_SEL_CHANGED, self.on_app_select, id=self.app_tree.GetId())
    39  self.app_tree.SetFocus()
    40  #self.app_tree.SelectItem(self.app_tree.GetFirstVisibleItem()) #<--commenting out this line removes the issue with wxPython 3.0
    41  self.panel_left_sizer.Add(self.app_tree, 1, wx.EXPAND)
        ...

Temporary fix until true solution is determined.

**Comment by rafaelesteller** [comment]
removed because too old
