### ISSUE TITLE
Update mission code for 2016

### ISSUE THREAD

**Issue by smosh** [ncsurobotics/seawolf#37]

**Comment by smosh** [comment]
Gate:
- Remove timeout and premature completion issues based on footage collected during 2015 competition: COMPLETE
- Test Gate with properly tuned PID system: IN PROGRESS
- Setup Gate mission to terminate when poles reach edge of screen, or when gate is not seen for a long time: IN PROGRESS

Buoys:
- Get it working. IN PROGRESS
- Modify for pull down scuttle ship option: TODO

Integration:
- Get Gate->Path transition working and tested: IN PROGRESS

Sequences:
- Gate->Path:                          COMPLETE
- 15secDeadReackon->Path:  TODO
- Path->Angle->Strafe:            TODO
- Path->Bouys:                        IN PROGRESS
- VisionAssistedDeadReackon->Torpedos
- Bouys->Path:                        TODO

**Comment by rafaelesteller** [comment]
removed because too old
