### ISSUE TITLE
Update vision code for 2016

### ISSUE THREAD

**Issue by smosh** [ncsurobotics/seawolf#38]
#5

**Comment by smosh** [comment]
Gate:
- Optimized for orange color. Added color adjustement parameter for adaptive threshold step: COMPLETE.

Path:
- See if it works: COMPLETE

Bins:
- See if it works: COMPLETE

Buoys:
- Color detection is inaccurate. Fix it: TODO

Torpedos:
- Lay down initial code for target detection and identification: TODO

**Comment by rafaelesteller** [comment]
removed because too old
