### ISSUE TITLE
Toggle Mission frame rate

### ISSUE THREAD

**Issue by bjfisher1** [ncsurobotics/seawolf#67]
Create ability to control fps of video streams in order to reduce heat problems.

Look for old SVR method to adjust fps or modify it to do so

**Comment by bjfisher1** [comment]
This issue may be easier to fix by having vision objects have an image state that only gets updated every 1/fps seconds. Vision objects could extend a super class that keeps up with updating the state according to fps.

**Comment by bjfisher1** [comment]
Temporarily solved with sleep() call in mission run.py.

- Need to test if this works properly on a live camera feed.

- Need to test if this helps overheating problem.

**Comment by bfisher1** [comment]
Tested through webcam. Delay seems tolerable and not bad enough to put robot out of sync with missions.
